### ISSUE TITLE
Home modules not installed

### ISSUE THREAD

**Issue by jcf** [yelite/lite-system#3]
Hello again Ye Lite,

I've come up against another issue that seems to stem from Home Manager not being configured out of the box.

I can reproduce this issue with a trivial [system zsh module][] and [home git module][] where I conditionally enable each via a `mkEnableOption`.

[system zsh module]: https://github.com/jcf/lite-system-emacs-overlay/blob/8726633e171139f143acf04d9fe8baa66bed10ad/system/zsh/default.nix
[home git module]: https://github.com/jcf/lite-system-emacs-overlay/blob/8726633e171139f143acf04d9fe8baa66bed10ad/home/git/default.nix

``` nix
{ config
, lib
, ...
}:
let
  inherit (lib) mkEnableOption mkIf;
  cfg = config.my.system.zsh;
in
{
  options.my.system.zsh = {
    enable = mkEnableOption "zsh";
  };

  config = mkIf cfg.enable {
    programs.zsh.enable = true;
  };
}
```

``` nix
{ config
, lib
, ...
}:
let
  inherit (lib) mkEnableOption mkIf;
  cfg = config.my.home.git;
in
{
  options.my.home.git = {
    enable = mkEnableOption "git";
  };

  config = mkIf cfg.enable {
    programs.git.enable = true;
  };
}
```

I toggle these on in my [host configuration][] and only see the system module taking affect.

``` nix
{ ... }: {
  my = {
    system = {
      zsh.enable = true;
    };

    home = {
      git.enable = true;
    };
  };
}
```

[host configuration]: https://github.com/jcf/lite-system-emacs-overlay/blob/8726633e171139f143acf04d9fe8baa66bed10ad/host/max/default.nix

I might be missing something; maybe I have more work to do with Home Manager to get modules showing up in the host config?

https://github.com/jcf/lite-system-emacs-overlay/tree/main#home-modules

**Comment by yelite** [comment]
Try to import this in your system module,

```nix
{config, ...}: {
  home-manager = {
    sharedModules = [
      {
        my.home = config.my.home;
      }
    ];
  };
}
```

The problem is that home manager modules are evaluated as submodule under NixOS modules. This means the options and config of home manager modules are separate from the ones of system module.

This seems to be a common problem when building system config with NixOS and home manager. I have a similar module in my config too (https://github.com/yelite/system-config/blob/a46c05d5c9ebfc49b3ffccdc6b8382f48e26fe7a/system/home-manager.nix#L43). It would be great if lite-system can do this automatically, but I don't have good idea on how to have a clean and simple API for it.

**Comment by jcf** [comment]
Ahh, I see! So the home modules aren't aware of any of the options declared at the system level.

I've tried adding a `sharedModule` but that seems to pass in something a lot more empty than expected.

``` nix 
{ lib
, config
, ...
}: {
  config = {
    home-manager = {
      users.${config.my.username} = { };
      sharedModules = [{ my = config.my; }];
    };
  };
}
```

```
         at /nix/store/aiv01710wqn2b7hms2253d1cq89kdzh8-source/lib/modules.nix:242:72:

          241|           # For definitions that have an associated option
          242|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          243|

       … while evaluating the option `my.home':

       … from call site

         at /nix/store/aiv01710wqn2b7hms2253d1cq89kdzh8-source/lib/modules.nix:844:59:

          843|       if isDefined then
          844|         if all (def: type.check def.value) defsFinal then type.merge loc defsFinal
             |                                                           ^
          845|         else let allInvalid = filter (def: ! type.check def.value) defsFinal;

       … while calling 'merge'

         at /nix/store/aiv01710wqn2b7hms2253d1cq89kdzh8-source/lib/types.nix:762:22:

          761|         check = x: isAttrs x || isFunction x || path.check x;
          762|         merge = loc: defs:
             |                      ^
          763|           (base.extendModules {

       error: The option `my.home.alacritty' does not exist. Definition values:
       - In `/nix/store/8xp12dvzjhzkxlkrfnw7gr2knyd6mz2f-host/max':
           {
             enable = true;
           }

       However there are no options defined in `my.home'. Are you sure you've
       declared your options properly? This can happen if you e.g. declared your options in `types.submodule'
       under `config' rather than `options'.
```

I'll see if I can reproduce in my minimal example repo.

Thanks for all the help, @yelite!

**Comment by jcf** [comment]
Thanks again, @yelite! I've applied your patch, and I'm able to build a result successfully.

I'm still missing the Git packages I was hoping Home Manager would install when enabled via the host configuration, and I'm perplexed as to why I can't pass in the `my.username`.

For this basic example it's not a huge problem, but as soon as I have email addresses, secrets etc. in my configuration, I'd love to be able to pass in all of `config.my`.

I've pushed your suggestions to my mini repo, and expect a green build soon enough. I might add a quick test to assert that the result is packed full of the requested goodies too.

Watch this space!

**Comment by jcf** [comment]
I got the [build passing][green] by adding an x86-specific host — a sample lite-system that builds a result via GitHub Actions.

[green]: https://github.com/jcf/lite-system-emacs-overlay/actions/runs/7174949872

There's still the problem of Git (from a home module) not actually being installed, which leads me to believe the `my.home` configuration isn't being passed around as I had hoped.

I've verified this [via CI][red] with a little `find ... | grep` step.

[red]: https://github.com/jcf/lite-system-emacs-overlay/actions/runs/7175039429/job/19537639225

I'll continue sluething to try to and prepare a sample we can use as documentation for future users of lite-system.

**Comment by yelite** [comment]
@jcf git is indeed installed. You can check it with
```bash
nix why-depends -a .#darwinConfigurations.aarch64-darwin.system .#darwinConfigurations.aarch64-darwin.config.home-manager.users.jcf.programs.git.package 
```

It should output
```
/nix/store/jablb7giccqx4m5kr5k17kj1b3hfssrd-darwin-system-24.05pre-git+darwin4.4b9b83d
├───/nix/store/09cwfgk4wxxh35fs0bm84waly1s2aifl-system-path
│   ├───/nix/store/6ypavfvrl3w3xq6d32z80075g8vyz785-darwin-option
│   │   └───/nix/store/rxpifxzrsjb0xfjrkrg16vm1876scqvj-git-2.42.0
│   ├───/nix/store/ad0l65c4hylyj917nx60ncgzw90ddrkr-darwin-rebuild
│   │   └───/nix/store/rxpifxzrsjb0xfjrkrg16vm1876scqvj-git-2.42.0
│   └───/nix/store/9wm3xwkvbhda2q8rrrgyl2f3f4bgm7qx-darwin-uninstaller
│       └───/nix/store/814r8w71i7agc18m67zs6hplwj93ygg7-darwin-system-24.05pre-git+darwin4
│           └───/nix/store/vdwnd71b6420hs973h2ljc3aiz3pm1f5-system-path
│               ├───/nix/store/6ypavfvrl3w3xq6d32z80075g8vyz785-darwin-option
│               └───/nix/store/ad0l65c4hylyj917nx60ncgzw90ddrkr-darwin-rebuild
└───/nix/store/83qdds8n0cy9nqyhljp5ysgvnghal0wg-activation-jcf
    └───/nix/store/km8xv23cy62fk50h7v34pcixcji7j9qy-home-manager-generation
        └───/nix/store/v1cmx2racg3rfd04wx7br8dd8vxw07mh-home-manager-path
            └───/nix/store/rxpifxzrsjb0xfjrkrg16vm1876scqvj-git-2.42.0
```

You can also check the evaluation result with `nix repl`.
```
❯ nix repl
Welcome to Nix 2.18.1. Type :? for help.

nix-repl> :lf .                                                                                 
Added 22 variables.

nix-repl> darwinConfigurations.aarch64-darwin.config.home-manager.users.jcf.programs.git.enable
true
```

`find ... | grep` does not work if you want to find any package in the dependency graph. The build result points to `/nix/store/jablb7giccqx4m5kr5k17kj1b3hfssrd-darwin-system-24.05pre-git+darwin4.4b9b83d` and the content in it will only contain the direct dependencies of this package.

If you can't use the git from nix in your shell, it's probably due to a different shell being used.

**Comment by jcf** [comment]
Thanks for the pointer, @yelite! I didn't realise that the home-manager-managed dependencies wouldn't be so easily discoverable. That might well mean I have a working configuration as long as I don't need to share configuration between system and home directory.

Unfortunately, I can't see myself duplicating information like my username, email address, etc. in more than one place, and there doesn't seem to be any way to pass a simple map of `config.my` to Home Manager.

I'll keep experimenting with this, but given the cryptic errors and cached failures, progress is slower than I'd like. I hope you don't mind bearing with me!

**Comment by jcf** [comment]
Someone on Discord pointed me towards `osConfig` and suggested I avoid passing things through the module system twice.

I'm probably going to take a break from Nix for a while at this point because I'm spending too much time setting up the basics and not enough time on meaningful work.

I haven't solved this problem fully, and apologise to anyone who finds themselves here hoping for a solution, but will close this to take the work off Lite Ye's plate as it's not a problem specific to lite-system.
